### PR TITLE
add update url

### PR DESCRIPTION
**Pull request by Delphox**
for usage in violentmonkey/tampermonkey

### CODE REVIEW

**Comment by Procyon-b** [comment]
It shouldn't be necessary. I haven't had any problem with tampermonkey updating to the new version of the script.
Did you have a problem?

**Comment by Delphox** [comment]
Oh you're right actually. I honestly just assumed it was necessary, but it seems both Tampermonkey and Violentmonkey remember the url it was installed from so it uses it as a fallback for updates in case the update_url isn't declared in the script itself (although this is probably non-standard behavior).

I guess it's up to you, on one hand having the update_url declared would make it more compatible (in case someone installs a saved copy or something), but I dunno if this would mess up with your original PR in case this is ever getting merged upstream (in this case it's not worth it). So yea, your call.

**Comment by Procyon-b** [comment]
When you look at the userscripts installed from greasyfork.org and other similar sources, you'll see that almost none of them include that header. (And from the author POV you don't know the actual url when you first post the script)
From how I see it, it is useful when you want to divert the "source" of the script somewhere else. Or if you post the code of the script in forums and expect people to copy-paste into their userscript manager (I haven't verified that assumption).

**Comment by Delphox** [comment]
Oh yea that makes sense. I'll close it then. Thanks for clarifying that it's not necessary!

**Comment by Procyon-b** [comment]
It is not necessary here (at least as far as we know), but it can sometimes be useful.

**Pull request closed without merging**
